-- Migration: Create job_analyses table for Job Description Analysis and Resume Comparison history
create table if not exists public.job_analyses (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  job_title text not null,
  company text default 'Target Company',
  job_description text not null,
  extracted_skills text[] default '{}',
  extracted_responsibilities text[] default '{}',
  match_score integer,
  analysis_type text not null default 'jd_analysis' check (analysis_type in ('jd_analysis', 'resume_comparison')),
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable RLS
alter table public.job_analyses enable row level security;

-- Policies for job_analyses
drop policy if exists "Users can read their job analyses" on public.job_analyses;
create policy "Users can read their job analyses"
  on public.job_analyses for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = job_analyses.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can insert their job analyses" on public.job_analyses;
create policy "Users can insert their job analyses"
  on public.job_analyses for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = job_analyses.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can delete their job analyses" on public.job_analyses;
create policy "Users can delete their job analyses"
  on public.job_analyses for delete to authenticated
  using (exists (select 1 from public.profiles where profiles.id = job_analyses.profile_id and profiles.user_id = auth.uid()));
