-- Extend the existing interview tables without replacing the established API contract.
alter table public.mock_interviews
  add column if not exists current_question integer not null default 0,
  add column if not exists role_knowledge_score integer,
  add column if not exists clarity_score integer,
  add column if not exists summary text,
  add column if not exists strengths jsonb not null default '[]'::jsonb,
  add column if not exists weaknesses jsonb not null default '[]'::jsonb,
  add column if not exists recommendations jsonb not null default '[]'::jsonb;

alter table public.mock_interview_questions
  add column if not exists question_number integer,
  add column if not exists expected_topics jsonb not null default '[]'::jsonb,
  add column if not exists correctness integer,
  add column if not exists relevance integer,
  add column if not exists clarity integer,
  add column if not exists technical_depth integer,
  add column if not exists ideal_answer text,
  add column if not exists improvement_tips jsonb not null default '[]'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table public.mock_interviews drop constraint if exists mock_interviews_interview_type_check;
alter table public.mock_interviews add constraint mock_interviews_interview_type_check
  check (interview_type in ('Technical', 'Coding', 'Behavioral', 'HR', 'System Design', 'Project-Based', 'Mixed', 'Role-specific'));
alter table public.mock_interviews drop constraint if exists mock_interviews_difficulty_check;
alter table public.mock_interviews add constraint mock_interviews_difficulty_check
  check (difficulty in ('Beginner', 'Intermediate', 'Advanced', 'Expert', 'Easy', 'Medium', 'Hard'));
alter table public.mock_interviews drop constraint if exists mock_interviews_duration_minutes_check;
alter table public.mock_interviews add constraint mock_interviews_duration_minutes_check
  check (duration_minutes between 5 and 180);

create table if not exists public.interview_reports (
  id bigint generated by default as identity primary key,
  interview_id bigint not null unique references public.mock_interviews(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  target_role text,
  interview_type text,
  difficulty text,
  question_count integer,
  answered_questions integer,
  completed_at timestamptz,
  overall_score integer,
  technical_score integer,
  communication_score integer,
  problem_solving_score integer,
  role_knowledge_score integer,
  clarity_score integer,
  summary text,
  strengths jsonb not null default '[]'::jsonb,
  weaknesses jsonb not null default '[]'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  topic_performance jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.interview_answers (
  id bigint generated by default as identity primary key,
  interview_id bigint not null references public.mock_interviews(id) on delete cascade,
  question_id bigint not null references public.mock_interview_questions(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  answer text not null,
  score integer,
  correctness integer,
  relevance integer,
  clarity integer,
  technical_depth integer,
  feedback text,
  ideal_answer text,
  improvement_tips jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (interview_id, question_id)
);

alter table public.interview_reports
  add column if not exists target_role text,
  add column if not exists interview_type text,
  add column if not exists difficulty text,
  add column if not exists question_count integer,
  add column if not exists answered_questions integer,
  add column if not exists completed_at timestamptz;

alter table public.interview_reports enable row level security;
alter table public.interview_answers enable row level security;

drop policy if exists "Users can manage their interview reports" on public.interview_reports;
create policy "Users can manage their interview reports" on public.interview_reports for all to authenticated
  using (exists (select 1 from public.profiles where profiles.id = interview_reports.profile_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.profiles where profiles.id = interview_reports.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can manage their interview answers" on public.interview_answers;
create policy "Users can manage their interview answers" on public.interview_answers for all to authenticated
  using (exists (select 1 from public.profiles where profiles.id = interview_answers.profile_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.profiles where profiles.id = interview_answers.profile_id and profiles.user_id = auth.uid()));

create index if not exists interview_reports_profile_created_idx on public.interview_reports(profile_id, created_at desc);
create index if not exists interview_answers_profile_created_idx on public.interview_answers(profile_id, created_at desc);
create index if not exists interview_answers_interview_idx on public.interview_answers(interview_id, created_at);
