-- Foundational profile and catalog tables required by all later migrations.
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text,
  education text,
  branch text,
  graduation_year text,
  experience text,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_user_id_idx on public.profiles(user_id);

create or replace function public.set_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute function public.set_profiles_updated_at();

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_skills (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  proficiency integer not null default 0 check (proficiency between 0 and 100),
  created_at timestamptz not null default now(),
  unique (profile_id, skill_id)
);

create index if not exists user_skills_profile_id_idx on public.user_skills(profile_id);

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  profile_id bigint not null unique references public.profiles(id) on delete cascade,
  preferred_industries text,
  preferred_work_mode text,
  preferred_locations text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_user_preferences_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_preferences_updated_at on public.user_preferences;
create trigger user_preferences_updated_at
before update on public.user_preferences
for each row execute function public.set_user_preferences_updated_at();

alter table public.profiles enable row level security;
alter table public.skills enable row level security;
alter table public.user_skills enable row level security;
alter table public.user_preferences enable row level security;

create policy "Users can read their profile"
on public.profiles for select to authenticated
using (user_id = auth.uid());
create policy "Users can create their profile"
on public.profiles for insert to authenticated
with check (user_id = auth.uid());
create policy "Users can update their profile"
on public.profiles for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());
create policy "Users can delete their profile"
on public.profiles for delete to authenticated
using (user_id = auth.uid());

create policy "Authenticated users can read skills"
on public.skills for select to authenticated
using (true);
create policy "Authenticated users can add skills"
on public.skills for insert to authenticated
with check (true);

create policy "Users can read their skills"
on public.user_skills for select to authenticated
using (exists (select 1 from public.profiles where profiles.id = user_skills.profile_id and profiles.user_id = auth.uid()));
create policy "Users can add their skills"
on public.user_skills for insert to authenticated
with check (exists (select 1 from public.profiles where profiles.id = user_skills.profile_id and profiles.user_id = auth.uid()));
create policy "Users can update their skills"
on public.user_skills for update to authenticated
using (exists (select 1 from public.profiles where profiles.id = user_skills.profile_id and profiles.user_id = auth.uid()))
with check (exists (select 1 from public.profiles where profiles.id = user_skills.profile_id and profiles.user_id = auth.uid()));
create policy "Users can delete their skills"
on public.user_skills for delete to authenticated
using (exists (select 1 from public.profiles where profiles.id = user_skills.profile_id and profiles.user_id = auth.uid()));

create policy "Users can read their preferences"
on public.user_preferences for select to authenticated
using (exists (select 1 from public.profiles where profiles.id = user_preferences.profile_id and profiles.user_id = auth.uid()));
create policy "Users can create their preferences"
on public.user_preferences for insert to authenticated
with check (exists (select 1 from public.profiles where profiles.id = user_preferences.profile_id and profiles.user_id = auth.uid()));
create policy "Users can update their preferences"
on public.user_preferences for update to authenticated
using (exists (select 1 from public.profiles where profiles.id = user_preferences.profile_id and profiles.user_id = auth.uid()))
with check (exists (select 1 from public.profiles where profiles.id = user_preferences.profile_id and profiles.user_id = auth.uid()));
create policy "Users can delete their preferences"
on public.user_preferences for delete to authenticated
using (exists (select 1 from public.profiles where profiles.id = user_preferences.profile_id and profiles.user_id = auth.uid()));
