-- Migration: Create tables for job matching persistence and application tracking

-- 1. Create career_goals table for persistent target role and preferences
create table if not exists public.career_goals (
  id bigint generated by default as identity primary key,
  profile_id bigint not null unique references public.profiles(id) on delete cascade,
  target_role text not null,
  preferred_location text,
  work_preference text check (work_preference in ('Remote', 'Hybrid', 'On-site', 'Any')),
  goal_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable RLS for career_goals
alter table public.career_goals enable row level security;

-- Policies for career_goals
drop policy if exists "Users can read their career goals" on public.career_goals;
create policy "Users can read their career goals"
  on public.career_goals for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_goals.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can upsert their career goals" on public.career_goals;
create policy "Users can upsert their career goals"
  on public.career_goals for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = career_goals.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can update their career goals" on public.career_goals;
create policy "Users can update their career goals"
  on public.career_goals for update to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_goals.profile_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.profiles where profiles.id = career_goals.profile_id and profiles.user_id = auth.uid()));

-- 2. Create saved_jobs table for bookmarked opportunities
create table if not exists public.saved_jobs (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  job_id text not null,
  created_at timestamptz not null default now(),
  unique (profile_id, job_id)
);

-- Enable RLS for saved_jobs
alter table public.saved_jobs enable row level security;

-- Policies for saved_jobs
drop policy if exists "Users can read their saved jobs" on public.saved_jobs;
create policy "Users can read their saved jobs"
  on public.saved_jobs for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = saved_jobs.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can save jobs" on public.saved_jobs;
create policy "Users can save jobs"
  on public.saved_jobs for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = saved_jobs.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can remove saved jobs" on public.saved_jobs;
create policy "Users can remove saved jobs"
  on public.saved_jobs for delete to authenticated
  using (exists (select 1 from public.profiles where profiles.id = saved_jobs.profile_id and profiles.user_id = auth.uid()));

-- 3. Create job_applications table for application tracking
create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  job_id text not null,
  status text not null default 'saved' check (status in ('saved', 'applied', 'assessment', 'interview', 'rejected', 'offer')),
  applied_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, job_id)
);

-- Enable RLS for job_applications
alter table public.job_applications enable row level security;

-- Policies for job_applications
drop policy if exists "Users can read their job applications" on public.job_applications;
create policy "Users can read their job applications"
  on public.job_applications for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = job_applications.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can create job applications" on public.job_applications;
create policy "Users can create job applications"
  on public.job_applications for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = job_applications.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can update their job applications" on public.job_applications;
create policy "Users can update their job applications"
  on public.job_applications for update to authenticated
  using (exists (select 1 from public.profiles where profiles.id = job_applications.profile_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.profiles where profiles.id = job_applications.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can delete their job applications" on public.job_applications;
create policy "Users can delete their job applications"
  on public.job_applications for delete to authenticated
  using (exists (select 1 from public.profiles where profiles.id = job_applications.profile_id and profiles.user_id = auth.uid()));

-- 4. Update career_analyses table to add updated_at trigger if not exists
create or replace function public.set_career_analyses_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists career_analyses_updated_at on public.career_analyses;
create trigger career_analyses_updated_at
before update on public.career_analyses
for each row execute function public.set_career_analyses_updated_at();

-- Add updated_at column to career_analyses if it doesn't exist
alter table public.career_analyses add column if not exists updated_at timestamptz default now();

-- Set updated_at for existing rows
update public.career_analyses set updated_at = created_at where updated_at is null;

-- Make it not nullable
alter table public.career_analyses alter column updated_at set not null;
