-- Migration: Add isolated career_milestones and career_timeline_events for Phase 11 Intelligent Career Coach & Personalization Engine

-- 1. Create public.career_milestones table
create table if not exists public.career_milestones (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  user_id uuid default auth.uid(),
  milestone_key text not null,
  title text not null,
  description text,
  category text not null default 'General',
  status text not null default 'Locked' check (status in ('Completed', 'In Progress', 'Locked')),
  unlocked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (profile_id, milestone_key)
);

-- Indexing for fast profile queries
create index if not exists idx_career_milestones_profile_status on public.career_milestones(profile_id, status);

-- Enable RLS for career_milestones
alter table public.career_milestones enable row level security;

-- Policies for career_milestones (Strict user isolation)
drop policy if exists "Users can read their career milestones" on public.career_milestones;
create policy "Users can read their career milestones"
  on public.career_milestones for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_milestones.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can insert career milestones" on public.career_milestones;
create policy "Users can insert career milestones"
  on public.career_milestones for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = career_milestones.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can update their career milestones" on public.career_milestones;
create policy "Users can update their career milestones"
  on public.career_milestones for update to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_milestones.profile_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.profiles where profiles.id = career_milestones.profile_id and profiles.user_id = auth.uid()));


-- 2. Create public.career_timeline_events table
create table if not exists public.career_timeline_events (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  user_id uuid default auth.uid(),
  event_type text not null, -- e.g. 'profile_updated', 'resume_uploaded', 'skill_added', 'gap_completed', 'milestone_unlocked', 'application_sent', 'interview_scheduled'
  title text not null,
  description text,
  category text not null default 'General',
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Indexing for timeline events
create index if not exists idx_career_timeline_profile_time on public.career_timeline_events(profile_id, created_at desc);

-- Enable RLS for career_timeline_events
alter table public.career_timeline_events enable row level security;

-- Policies for career_timeline_events
drop policy if exists "Users can read their timeline events" on public.career_timeline_events;
create policy "Users can read their timeline events"
  on public.career_timeline_events for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_timeline_events.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can insert timeline events" on public.career_timeline_events;
create policy "Users can insert timeline events"
  on public.career_timeline_events for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = career_timeline_events.profile_id and profiles.user_id = auth.uid()));
