-- Migration: Add isolated career_job_applications and job_application_events for Phase 10 Application Tracker & Career Action Center

-- 1. Create public.career_job_applications table
create table if not exists public.career_job_applications (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  user_id uuid default auth.uid(),
  company_name text not null,
  job_title text not null,
  job_url text,
  location text,
  employment_type text default 'Full-time',
  salary_text text,
  description text,
  source text default 'Manual',
  status text not null default 'saved' check (status in ('saved', 'applied', 'screening', 'interview', 'offer', 'rejected', 'withdrawn')),
  priority text not null default 'MEDIUM' check (priority in ('HIGH', 'MEDIUM', 'LOW')),
  applied_at timestamptz,
  interview_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, company_name, job_title)
);

-- Indexing for fast dashboard & list queries
create index if not exists idx_career_job_apps_profile_status on public.career_job_applications(profile_id, status);
create index if not exists idx_career_job_apps_profile_priority on public.career_job_applications(profile_id, priority);
create index if not exists idx_career_job_apps_created_at on public.career_job_applications(created_at desc);

-- Enable RLS for career_job_applications
alter table public.career_job_applications enable row level security;

-- Policies for career_job_applications (Strict user isolation)
drop policy if exists "Users can read their career job applications" on public.career_job_applications;
create policy "Users can read their career job applications"
  on public.career_job_applications for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_job_applications.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can create career job applications" on public.career_job_applications;
create policy "Users can create career job applications"
  on public.career_job_applications for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = career_job_applications.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can update their career job applications" on public.career_job_applications;
create policy "Users can update their career job applications"
  on public.career_job_applications for update to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_job_applications.profile_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.profiles where profiles.id = career_job_applications.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can delete their career job applications" on public.career_job_applications;
create policy "Users can delete their career job applications"
  on public.career_job_applications for delete to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_job_applications.profile_id and profiles.user_id = auth.uid()));


-- 2. Create public.job_application_events table for timeline tracking
create table if not exists public.job_application_events (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.career_job_applications(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  event_type text not null, -- e.g. 'created', 'applied', 'status_change', 'follow_up', 'interview_scheduled', 'note'
  note text,
  created_at timestamptz not null default now()
);

-- Indexing for event timeline
create index if not exists idx_job_app_events_app_id on public.job_application_events(application_id, created_at desc);

-- Enable RLS for job_application_events
alter table public.job_application_events enable row level security;

-- Policies for job_application_events
drop policy if exists "Users can read their application events" on public.job_application_events;
create policy "Users can read their application events"
  on public.job_application_events for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = job_application_events.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can create application events" on public.job_application_events;
create policy "Users can create application events"
  on public.job_application_events for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = job_application_events.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can delete their application events" on public.job_application_events;
create policy "Users can delete their application events"
  on public.job_application_events for delete to authenticated
  using (exists (select 1 from public.profiles where profiles.id = job_application_events.profile_id and profiles.user_id = auth.uid()));
