-- Migration: Create CareerAI tables for Resume Analyses, Career Analyses, and Interview Sessions.

-- 1. Create resume_analyses table
create table if not exists public.resume_analyses (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  filename text not null,
  file_size integer not null,
  page_count integer not null,
  character_count integer not null,
  overall_score integer not null,
  ats_score integer not null,
  keyword_score integer not null,
  formatting_score integer not null,
  detected_skills jsonb not null default '[]'::jsonb,
  strengths jsonb not null default '[]'::jsonb,
  improvements jsonb not null default '[]'::jsonb,
  projects jsonb not null default '[]'::jsonb,
  education_experience jsonb not null default '[]'::jsonb,
  missing_skills jsonb not null default '[]'::jsonb,
  ats_recommendations jsonb not null default '[]'::jsonb,
  ai_summary text not null,
  created_at timestamptz not null default now()
);

-- Enable RLS for resume_analyses
alter table public.resume_analyses enable row level security;

-- Policies for resume_analyses
drop policy if exists "Users can read their own resume analyses" on public.resume_analyses;
create policy "Users can read their own resume analyses"
  on public.resume_analyses for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = resume_analyses.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can insert their own resume analyses" on public.resume_analyses;
create policy "Users can insert their own resume analyses"
  on public.resume_analyses for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = resume_analyses.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can delete their own resume analyses" on public.resume_analyses;
create policy "Users can delete their own resume analyses"
  on public.resume_analyses for delete to authenticated
  using (exists (select 1 from public.profiles where profiles.id = resume_analyses.profile_id and profiles.user_id = auth.uid()));

-- 2. Create career_analyses table
create table if not exists public.career_analyses (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  target_role text not null,
  career_summary text not null,
  strengths jsonb not null default '[]'::jsonb,
  skill_gaps jsonb not null default '[]'::jsonb,
  recommended_skills jsonb not null default '[]'::jsonb,
  learning_strategy jsonb not null default '[]'::jsonb,
  recommended_roles jsonb not null default '[]'::jsonb,
  interview_preparation jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- Enable RLS for career_analyses
alter table public.career_analyses enable row level security;

-- Policies for career_analyses
drop policy if exists "Users can read their own career analyses" on public.career_analyses;
create policy "Users can read their own career analyses"
  on public.career_analyses for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = career_analyses.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can insert their own career analyses" on public.career_analyses;
create policy "Users can insert their own career analyses"
  on public.career_analyses for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = career_analyses.profile_id and profiles.user_id = auth.uid()));

-- 3. Create interview_sessions table
create table if not exists public.interview_sessions (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  job_role text not null,
  experience_level text not null,
  interview_type text not null,
  score integer not null,
  messages jsonb not null default '[]'::jsonb,
  feedback jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable RLS for interview_sessions
alter table public.interview_sessions enable row level security;

-- Policies for interview_sessions
drop policy if exists "Users can read their own interview sessions" on public.interview_sessions;
create policy "Users can read their own interview sessions"
  on public.interview_sessions for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = interview_sessions.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can insert their own interview sessions" on public.interview_sessions;
create policy "Users can insert their own interview sessions"
  on public.interview_sessions for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = interview_sessions.profile_id and profiles.user_id = auth.uid()));

-- 4. Seed initial skills into the skills table if it is empty
insert into public.skills (name, category)
select name, category from (
  values
    ('Python', 'Programming'),
    ('Java', 'Programming'),
    ('JavaScript', 'Programming'),
    ('React', 'Frontend'),
    ('SQL', 'Data'),
    ('C++', 'Programming'),
    ('Git', 'Tools'),
    ('HTML', 'Frontend'),
    ('CSS', 'Frontend'),
    ('Node.js', 'Backend'),
    ('Machine Learning', 'Data'),
    ('Data Structures', 'Core CS'),
    ('System Design', 'Core CS'),
    ('TypeScript', 'Programming'),
    ('Docker', 'Tools'),
    ('AWS', 'Tools'),
    ('PostgreSQL', 'Data'),
    ('Express.js', 'Backend'),
    ('Power BI', 'Data'),
    ('Kubernetes', 'Tools'),
    ('Linux', 'Tools')
) as new_skills(name, category)
where not exists (select 1 from public.skills);
