create table if not exists public.roadmap_progress (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  roadmap_item_id text not null,
  status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'completed')),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, roadmap_item_id)
);

create or replace function public.set_roadmap_progress_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists roadmap_progress_updated_at on public.roadmap_progress;
create trigger roadmap_progress_updated_at
before update on public.roadmap_progress
for each row execute function public.set_roadmap_progress_updated_at();

alter table public.roadmap_progress enable row level security;

drop policy if exists "Users can read their roadmap progress" on public.roadmap_progress;
create policy "Users can read their roadmap progress"
on public.roadmap_progress
for select
to authenticated
using (exists (select 1 from public.profiles where profiles.id = roadmap_progress.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can create their roadmap progress" on public.roadmap_progress;
create policy "Users can create their roadmap progress"
on public.roadmap_progress
for insert
to authenticated
with check (exists (select 1 from public.profiles where profiles.id = roadmap_progress.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can update their roadmap progress" on public.roadmap_progress;
create policy "Users can update their roadmap progress"
on public.roadmap_progress
for update
to authenticated
using (exists (select 1 from public.profiles where profiles.id = roadmap_progress.profile_id and profiles.user_id = auth.uid()))
with check (exists (select 1 from public.profiles where profiles.id = roadmap_progress.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can delete their roadmap progress" on public.roadmap_progress;
create policy "Users can delete their roadmap progress"
on public.roadmap_progress
for delete
to authenticated
using (exists (select 1 from public.profiles where profiles.id = roadmap_progress.profile_id and profiles.user_id = auth.uid()));
