-- Isolated, non-destructive knowledge base for future CareerAI retrieval.
create extension if not exists vector with schema extensions;

create table if not exists public.career_knowledge_chunks (
  id bigint generated by default as identity primary key,
  title text not null,
  user_id uuid references auth.users(id) on delete cascade,
  source_id text,
  category text not null check (category in ('career_roles', 'skills', 'technologies', 'interview_topics', 'learning_resources', 'career_guidance', 'industry_trends', 'project_guidance')),
  role text,
  skill text,
  technology text,
  difficulty text,
  source text,
  source_type text,
  tags jsonb not null default '[]'::jsonb,
  content text not null,
  chunk_index integer not null check (chunk_index >= 0),
  content_hash text not null,
  embedding extensions.vector(128) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (content_hash, chunk_index)
);

alter table public.career_knowledge_chunks
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists source_id text;

create index if not exists career_knowledge_category_idx on public.career_knowledge_chunks(category);
create index if not exists career_knowledge_role_idx on public.career_knowledge_chunks(role);
create index if not exists career_knowledge_skill_idx on public.career_knowledge_chunks(skill);
create index if not exists career_knowledge_embedding_idx
  on public.career_knowledge_chunks using hnsw (embedding extensions.vector_cosine_ops);

alter table public.career_knowledge_chunks enable row level security;
drop policy if exists "Authenticated users can read career knowledge" on public.career_knowledge_chunks;
create policy "Authenticated users can read career knowledge"
  on public.career_knowledge_chunks for select to authenticated using (user_id is null or user_id = auth.uid());
drop policy if exists "Users can insert their private career knowledge" on public.career_knowledge_chunks;
create policy "Users can insert their private career knowledge"
  on public.career_knowledge_chunks for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "Users can update their private career knowledge" on public.career_knowledge_chunks;
create policy "Users can update their private career knowledge"
  on public.career_knowledge_chunks for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.match_career_knowledge_chunks(
  query_embedding extensions.vector(128),
  match_count integer default 5,
  similarity_threshold real default 0.15,
  filter_category text default null,
  filter_role text default null,
  filter_skill text default null,
  filter_difficulty text default null,
  filter_user_id uuid default null
)
returns table (
  id bigint,
  title text,
  user_id uuid,
  source_id text,
  category text,
  role text,
  skill text,
  technology text,
  difficulty text,
  source text,
  source_type text,
  tags jsonb,
  content text,
  chunk_index integer,
  similarity real
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    knowledge.id,
    knowledge.title,
    knowledge.user_id,
    knowledge.source_id,
    knowledge.category,
    knowledge.role,
    knowledge.skill,
    knowledge.technology,
    knowledge.difficulty,
    knowledge.source,
    knowledge.source_type,
    knowledge.tags,
    knowledge.content,
    knowledge.chunk_index,
    (1 - (knowledge.embedding <=> query_embedding))::real as similarity
  from public.career_knowledge_chunks as knowledge
  where (filter_category is null or knowledge.category = filter_category)
    and (knowledge.user_id is null or knowledge.user_id = auth.uid())
    and (filter_user_id is null or knowledge.user_id is null or knowledge.user_id = filter_user_id)
    and (filter_role is null or lower(knowledge.role) = lower(filter_role))
    and (filter_skill is null or lower(knowledge.skill) = lower(filter_skill))
    and (filter_difficulty is null or lower(knowledge.difficulty) = lower(filter_difficulty))
    and (1 - (knowledge.embedding <=> query_embedding)) >= similarity_threshold
  order by knowledge.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 20);
$$;
