-- Production mock interview sessions and per-question evaluations.
create table if not exists public.mock_interviews (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  target_role text not null,
  interview_type text not null check (interview_type in ('Technical', 'HR', 'Behavioral', 'Mixed', 'Role-specific')),
  difficulty text not null check (difficulty in ('Easy', 'Medium', 'Hard', 'Expert')),
  question_count integer not null default 5 check (question_count between 1 and 20),
  duration_minutes integer not null default 20 check (duration_minutes in (10, 20, 30)),
  status text not null default 'in_progress' check (status in ('in_progress', 'completed', 'abandoned')),
  total_questions integer not null check (total_questions between 1 and 20),
  completed_questions integer not null default 0 check (completed_questions >= 0),
  overall_score integer check (overall_score between 0 and 100),
  technical_score integer check (technical_score between 0 and 100),
  communication_score integer check (communication_score between 0 and 100),
  problem_solving_score integer check (problem_solving_score between 0 and 100),
  confidence_score integer check (confidence_score between 0 and 100),
  questions_answered integer not null default 0 check (questions_answered >= 0),
  questions_skipped integer not null default 0 check (questions_skipped >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mock_interview_questions (
  id bigint generated by default as identity primary key,
  interview_id bigint not null references public.mock_interviews(id) on delete cascade,
  question text not null,
  topic text not null,
  difficulty text not null,
  question_type text not null,
  expected_answer text,
  user_answer text,
  score integer check (score between 0 and 100),
  technical_score integer check (technical_score between 0 and 100),
  communication_score integer check (communication_score between 0 and 100),
  problem_solving_score integer check (problem_solving_score between 0 and 100),
  confidence_score integer check (confidence_score between 0 and 100),
  feedback jsonb not null default '{}'::jsonb,
  improvement text,
  response_time_seconds integer,
  time_taken_seconds integer,
  is_correct boolean,
  skipped boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.mock_interviews enable row level security;
alter table public.mock_interview_questions enable row level security;

drop policy if exists "Users can read their mock interviews" on public.mock_interviews;
create policy "Users can read their mock interviews" on public.mock_interviews for select to authenticated
  using (exists (select 1 from public.profiles where profiles.id = mock_interviews.profile_id and profiles.user_id = auth.uid()));
drop policy if exists "Users can create their mock interviews" on public.mock_interviews;
create policy "Users can create their mock interviews" on public.mock_interviews for insert to authenticated
  with check (exists (select 1 from public.profiles where profiles.id = mock_interviews.profile_id and profiles.user_id = auth.uid()));
drop policy if exists "Users can update their mock interviews" on public.mock_interviews;
create policy "Users can update their mock interviews" on public.mock_interviews for update to authenticated
  using (exists (select 1 from public.profiles where profiles.id = mock_interviews.profile_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.profiles where profiles.id = mock_interviews.profile_id and profiles.user_id = auth.uid()));

drop policy if exists "Users can read their mock interview questions" on public.mock_interview_questions;
create policy "Users can read their mock interview questions" on public.mock_interview_questions for select to authenticated
  using (exists (select 1 from public.mock_interviews join public.profiles on profiles.id = mock_interviews.profile_id where mock_interviews.id = mock_interview_questions.interview_id and profiles.user_id = auth.uid()));
drop policy if exists "Users can create their mock interview questions" on public.mock_interview_questions;
create policy "Users can create their mock interview questions" on public.mock_interview_questions for insert to authenticated
  with check (exists (select 1 from public.mock_interviews join public.profiles on profiles.id = mock_interviews.profile_id where mock_interviews.id = mock_interview_questions.interview_id and profiles.user_id = auth.uid()));
drop policy if exists "Users can update their mock interview questions" on public.mock_interview_questions;
create policy "Users can update their mock interview questions" on public.mock_interview_questions for update to authenticated
  using (exists (select 1 from public.mock_interviews join public.profiles on profiles.id = mock_interviews.profile_id where mock_interviews.id = mock_interview_questions.interview_id and profiles.user_id = auth.uid()))
  with check (exists (select 1 from public.mock_interviews join public.profiles on profiles.id = mock_interviews.profile_id where mock_interviews.id = mock_interview_questions.interview_id and profiles.user_id = auth.uid()));

create index if not exists mock_interviews_profile_created_idx on public.mock_interviews(profile_id, created_at desc);
create index if not exists mock_interviews_target_role_idx on public.mock_interviews(target_role);
create index if not exists mock_interview_questions_profile_idx on public.mock_interview_questions(interview_id, created_at);
create index if not exists mock_interview_questions_session_idx on public.mock_interview_questions(interview_id, created_at);
