create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  name text not null,
  description text not null,
  technologies jsonb not null default '[]'::jsonb,
  github_url text,
  live_url text,
  project_type text,
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_profile_id_updated_at_idx on public.projects(profile_id, updated_at desc);

create or replace function public.set_projects_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_updated_at on public.projects;
create trigger projects_updated_at before update on public.projects for each row execute function public.set_projects_updated_at();

alter table public.projects enable row level security;

drop policy if exists "Users can read their projects" on public.projects;
create policy "Users can read their projects" on public.projects for select to authenticated using (exists (select 1 from public.profiles where profiles.id = projects.profile_id and profiles.user_id = auth.uid()));
drop policy if exists "Users can create their projects" on public.projects;
create policy "Users can create their projects" on public.projects for insert to authenticated with check (exists (select 1 from public.profiles where profiles.id = projects.profile_id and profiles.user_id = auth.uid()));
drop policy if exists "Users can update their projects" on public.projects;
create policy "Users can update their projects" on public.projects for update to authenticated using (exists (select 1 from public.profiles where profiles.id = projects.profile_id and profiles.user_id = auth.uid())) with check (exists (select 1 from public.profiles where profiles.id = projects.profile_id and profiles.user_id = auth.uid()));
drop policy if exists "Users can delete their projects" on public.projects;
create policy "Users can delete their projects" on public.projects for delete to authenticated using (exists (select 1 from public.profiles where profiles.id = projects.profile_id and profiles.user_id = auth.uid()));
